//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPX519_ASPWebForm {
	
	
	public partial class items {
		
		protected System.Web.UI.WebControls.Literal ProductsList;
		
		protected System.Web.UI.HtmlControls.HtmlForm reviewForm;
		
		protected System.Web.UI.WebControls.TextBox tb2;
		
		protected System.Web.UI.WebControls.TextBox txt;
		
		protected System.Web.UI.WebControls.HiddenField prod;
		
		protected System.Web.UI.WebControls.Button but2;
		
		protected System.Web.UI.WebControls.Literal ProductsReview;
	}
}
