//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPX519_ASPWebForm {
	
	
	public partial class pages {
		
		protected System.Web.UI.WebControls.Literal ProductsList;
	}
}
